title: DCS Resources
email:
description: >- # this means to ignore newlines until "baseurl:"
  A set of DCS World resources, mods, links, info.
baseurl: "dcs-resources" # the subpath of your site, e.g. /blog
url: "https://lukaszgemborowski.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - mods.markdown
  - about.markdown
  - modules.markdown
